// <auto-generated/>
using Microsoft.AspNetCore.Components;
using PhotoExplorer.Components.Models;
using PhotoExplorer.Components.Services;
using System.Net.Http.Json;


namespace PhotoExplorer.Components;

public partial class PhotoList
{

    [Inject] private IPhotoService PhotoService { get; set; } = default!;

    private List<Photo>? _photos;

    protected override async Task OnInitializedAsync()
    {
       var photos = await PhotoService.GetPhotosFromApi();

        if (photos is not null)
        {
            _photos = photos;
        }
        else
        {
            _photos = new List<Photo>();
        }


        //try
        //{
        //    _photos = await client.GetFromJsonAsync<List<Photo>>("https://localhost:7198/photos");
        //    Console.WriteLine($"Nombre de photos récupérées : {_photos?.Count ?? 0}");
        //}
        //catch (Exception ex)
        //{
        //    Console.WriteLine($"Erreur lors du chargement des photos : {ex.Message}");
        //}
    }



}