// <auto-generated/>
using PhotoExplorer.Components.Models;
using System.Net.Http.Json;


namespace PhotoExplorer.Components;

public partial class PhotoList
{
    private List<Photo>? _photos;

    protected override async Task OnInitializedAsync()
    {
        using var client = new HttpClient();

        try
        {
            _photos = await client.GetFromJsonAsync<List<Photo>>("https://localhost:7198/photos");
            Console.WriteLine($"Nombre de photos récupérées : {_photos?.Count ?? 0}");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Erreur lors du chargement des photos : {ex.Message}");
        }
    }



}